---
name: ci
'on':
  push:
    paths:
    - "*"
  pull_request:
    branches:
    - master
  create:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.7'
        - '2.6'
        - '2.5'
        - '2.4'
        - jruby
    steps:
    - name: Check out repo
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{matrix.ruby}}"
    - name: Install latest bundler
      run: |
        gem install bundler --no-document
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Run all tests
      run: bundle exec rspec
